### ISSUE TITLE
N1打包后无法显示CPU架构和CPU状态，openwrt rootfs 编译注意事项里的已全部选上，貌似还少了某个组件

### ISSUE THREAD

**Issue by luckyreny** [unifreq/openwrt_packit#101]
openwrt rootfs 编译注意事项里提示的已全部选上。N1打包后无法显示CPU架构和CPU状态

以下是SSH登录信息
 PLATFORM: amlogic  SOC: s905d  BOARD: n1

Can't locate XSLoader.pm in @INC (you may need to install the XSLoader module) (@INC contains: /usr/lib/perl5/5.28) at /usr/lib/perl5/5.28/Time/HiRes.pm line 7.
BEGIN failed--compilation aborted at /usr/lib/perl5/5.28/Time/HiRes.pm line 7.
Compilation failed in require at /usr/bin/cpustat line 4.
BEGIN failed--compilation aborted at /usr/bin/cpustat line 4.
Can't locate XSLoader.pm in @INC (you may need to install the XSLoader module) (@INC contains: /usr/lib/perl5/5.28) at /usr/lib/perl5/5.28/Time/HiRes.pm line 7.
BEGIN failed--compilation aborted at /usr/lib/perl5/5.28/Time/HiRes.pm line 7.
Compilation failed in require at /usr/bin/cpustat line 4.
BEGIN failed--compilation aborted at /usr/bin/cpustat line 4.
Can't locate XSLoader.pm in @INC (you may need to install the XSLoader module) (@INC contains: /usr/lib/perl5/5.28) at /usr/lib/perl5/5.28/Time/HiRes.pm line 7.
BEGIN failed--compilation aborted at /usr/lib/perl5/5.28/Time/HiRes.pm line 7.
Compilation failed in require at /usr/bin/cpustat line 4.
BEGIN failed--compilation aborted at /usr/bin/cpustat line 4.
设备信息： Phicomm N1
CPU 型号:
运行时间:
环境温度:  47.0 °C              Can't locate XSLoader.pm in @INC (you may need to install the XSLoader module) (@INC contains: /usr/lib/perl5/5.28) at /usr/lib/perl5/5.28/Time/HiRes.pm line 7.
BEGIN failed--compilation aborted at /usr/lib/perl5/5.28/Time/HiRes.pm line 7.
Compilation failed in require at /usr/bin/cpustat line 4.
BEGIN failed--compilation aborted at /usr/bin/cpustat line 4.
当前频率:
内存已用:  9% of 1809MB         IP  地址:  192.168.1.1
启动存储:  17% of 511.0M        系统存储:  20% of 960.0M

**Comment by unifreq** [comment]
perlbase-time
perlbase-xlsoader

**Comment by luckyreny** [comment]
perlbase-time
perlbase-xlsoader
选上后，SSH出现以下错误，依然不行

Can't locate File/Glob.pm in @INC (you may need to install the File::Glob module) (@INC contains: /usr/lib/perl5/5.28) at /usr/bin/cpustat line 32.
BEGIN failed--compilation aborted at /usr/bin/cpustat line 32.
Can't locate File/Glob.pm in @INC (you may need to install the File::Glob module) (@INC contains: /usr/lib/perl5/5.28) at /usr/bin/cpustat line 32.
BEGIN failed--compilation aborted at /usr/bin/cpustat line 32.
Can't locate File/Glob.pm in @INC (you may need to install the File::Glob module) (@INC contains: /usr/lib/perl5/5.28) at /usr/bin/cpustat line 32.
BEGIN failed--compilation aborted at /usr/bin/cpustat line 32.

**Comment by luckyreny** [comment]
> perlbase-time perlbase-xlsoader

perlbase-time
perlbase-xlsoader
选上后，SSH出现以下错误，依然不行

在 @inc（您可能需要安装 File：：Glob 模块）（@inc包含：usr/lib/perl5/5.28）中找不到 File/Glob.pm，位于 /usr/bin/cpustat 第 32 行。
BEGIN 失败 - 编译在 /usr/bin/cpustat 第 32 行中止。
在 @inc（您可能需要安装 File：：Glob 模块）（@inc包含：usr/lib/perl5/5.28）中找不到 File/Glob.pm，位于 /usr/bin/cpustat 第 32 行。
BEGIN 失败 - 编译在 /usr/bin/cpustat 第 32 行中止。
在 @inc 中找不到 File/Glob.pm（您可能需要在 /usr/bin/cpustat 第 32 行安装 File：：Glob 模块）（@inc包含：/usr/lib/perl5/5.28）。
BEGIN 失败 - 编译在 /usr/bin/cpustat 第 32 行中止。
