### ISSUE TITLE
openwrt rootfs 编译注意事项里提示的已全部选上。perlbase-time perlbase-xlsoader已选，N1打包后无法显示CPU架构和CPU状态

### ISSUE THREAD

**Issue by luckyreny** [unifreq/openwrt_packit#112]
openwrt rootfs 编译注意事项里提示的已全部选上。
perlbase-time
perlbase-xlsoader
已选上
以下是SSH登录信息

 PLATFORM: amlogic  SOC: s905d  BOARD: n1

Can't locate File/Glob.pm in @INC (you may need to install the File::Glob module) (@INC contains: /usr/lib/perl5/5.28) at /usr/bin/cpustat line 32.
BEGIN failed--compilation aborted at /usr/bin/cpustat line 32.
Can't locate File/Glob.pm in @INC (you may need to install the File::Glob module) (@INC contains: /usr/lib/perl5/5.28) at /usr/bin/cpustat line 32.
BEGIN failed--compilation aborted at /usr/bin/cpustat line 32.
Can't locate File/Glob.pm in @INC (you may need to install the File::Glob module) (@INC contains: /usr/lib/perl5/5.28) at /usr/bin/cpustat line 32.
BEGIN failed--compilation aborted at /usr/bin/cpustat line 32.
设备信息： Phicomm N1
CPU 型号:
运行时间:
环境温度:  49.0 °C              Can't locate File/Glob.pm in @INC (you may need to install the File::Glob module) (@INC contains: /usr/lib/perl5/5.28) at /usr/bin/cpustat line 32.
BEGIN failed--compilation aborted at /usr/bin/cpustat line 32.
当前频率:
内存已用:  9% of 1809MB         IP  地址:  192.168.1.1
启动存储:  16% of 511.0M        系统存储:  23% of 960.0M

水平有限，.config里并没有搜索到Glob module.

**Comment by unifreq** [comment]
那就是还缺 perlbase-File这个包吧，早期的perl脚本不依赖这个，后面改过了。

**Comment by luckyreny** [comment]
> 那就是还缺 perlbase-File这个包吧，早期的perl脚本不依赖这个，后面改过了。

好的大佬，马上去试试

**Comment by luckyreny** [comment]
> 那就是还缺 perlbase-File这个包吧，早期的perl脚本不依赖这个，后面改过了。

已解决。谢谢大佬！
