### ISSUE TITLE
请问大佬知道这个是因为什么嘛？

### ISSUE THREAD

**Issue by yzj0405** [unifreq/openwrt_packit#114]
执行脚本的时候，提示这个信息：
patching file usr/lib/lua/luci/view/admin_status/index.htm
Reversed (or previously applied) patch detected!  Assume -R? [n] -f
Apply anyway? [n] y
Hunk #1 FAILED at 17.
Hunk #2 succeeded at 44 (offset 1 line).
Hunk #3 FAILED at 62.
Hunk #4 succeeded at 690 with fuzz 2 (offset 5 lines).
Hunk #5 FAILED at 752.
3 out of 5 hunks FAILED -- saving rejects to file usr/lib/lua/luci/view/admin_status/index.htm.rej
patching file etc/init.d/turboacc
patching file usr/lib/lua/luci/model/cbi/turboacc.lua
[+] Building 14.2s (5/5) FINISHED

本人环境，是做的玩客云的，没有完全按照大佬写的配置来，之前好好的，我改过主页的index.htm，但是也回退了，重新编译以后，还是提示这个。现在不知道哪里出的问题，烦请大佬帮忙看看。

**Comment by unifreq** [comment]
这是补丁不匹配，只影响首页状态显示
