### ISSUE TITLE
there are troubles with my openwrt of KVM

### ISSUE THREAD

**Issue by univerioiln233** [unifreq/openwrt_packit#133]
1.can not use the : init 6

init 6
[  285.500875] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[  285.509311] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[  285.519788] init: - preinit -
Press the [f] key and hit [enter] to enter failsafe mode
Press the [1], [2], [3] or [4] key and hit [enter] to select the debug level
[  289.737337] mount_root: mounting /dev/root
[  289.824292] BTRFS info (device vda2): using free space tree
[  289.826631] mount_root: loading kmods from internal overlay
[  290.107316] kmodloader: loading kernel modules from //etc/modules-boot.d/*
[  290.116314] kmodloader: done loading kernel modules from //etc/modules-boot.d/*
[  290.134722] block: attempting to load /etc/config/fstab
[  290.138443] block: extroot: unable to determine root device
[  290.142098] urandom-seed: Seeding with /etc/urandom.seed
Scanning for Btrfs filesystems
[  290.258213] procd: Failed to add object: Invalid argument

then,i waited for a long time.Nothing happened.
The system gets stuck here.
reboot works well,init 6 works worse

2.there is someting in the log all the time

daemon.err uhttpd: cat: can't open '/sys/devices/system/cpu/cpufreq/policy0/cpuinfo_cur_freq': No such file or directory
daemon.err uhttpd: expr: syntax error
daemon.err uhttpd: cat: can't open '/sys/class/thermal/thermal_zone0/temp': No such file or directory
daemon.err uhttpd: awk: cmd. line:1: Unexpected end of string

i saw these messeages almost 1000 times.

i try : rm /usr/bin/cpustat.....

**Comment by unifreq** [comment]
你说的这些都是无关紧要的，它没什么不良的影响。
另外，关于init 6， openwrt并不使用sysv init机制，所以这个命令是无效的。

**Comment by unifreq** [comment]
https://github.com/unifreq/openwrt_packit/commit/41aef6d9dfe2729494ea7210ed0e7e947f791aa8
这个commit顺便修复了下列问题 ：
daemon.err uhttpd: cat: can't open '/sys/devices/system/cpu/cpufreq/policy0/cpuinfo_cur_freq': No such file or directory
daemon.err uhttpd: expr: syntax error
daemon.err uhttpd: cat: can't open '/sys/class/thermal/thermal_zone0/temp': No such file or directory
daemon.err uhttpd: awk: cmd. line:1: Unexpected end of string
