### ISSUE TITLE
how to disable fuction:coremark.sh sysinfo.sh

### ISSUE THREAD

**Issue by univerioiln233** [unifreq/openwrt_packit#135]
rm -f /.snapshots/etc-000/coremark.sh
coremark.sh: Read-only file system

df /.snapshots/etc-000/coremark.sh
 can't find mount point

日志里一堆
can't open '/sys/class/thermal/thermal_zone0/temp': No such file or directory
daemon.err uhttpd[2612]: awk: cmd. line:1: Unexpected end of string
daemon.err uhttpd[2612]: cat: can'topen'/sys/devices/system/cpu/cpufreq/policy0/cpuinfo_cur_freq':
 另外个人不需要天天跑分，看频率。希望加一个开关选项

**Comment by unifreq** [comment]
跑分只会运行一次，是用cron定时任务执行的。
另外，/.snapshots/etc-000是初始快照，用来做系统恢复的。不要去动它
