### ISSUE TITLE
代码重复?

### ISSUE THREAD

**Issue by univerioiln233** [unifreq/openwrt_packit#136]
为什么qemu-aarch64.env里有两个irq？另外，我是门外汉.....
# 20201212 add
BAL_CONFIG="${WORK_HOME}/files/qemu-aarch64/balance_irq"

# 20220801 add
BALANCE_IRQ_HOME="${WORK_HOME}/files/qemu-aarch64/balance-irq"

**Comment by unifreq** [comment]
一个是文件，一个是目录，文件的已废弃了
