### ISSUE TITLE
关于usb无线网卡rtl8811cu的适配问题

### ISSUE THREAD

**Issue by gforce1206** [unifreq/openwrt_packit#179]
开发者大佬，你好，我尝试过用@lean和@immortalwrt源码编译，编译时已经加入kmod-rtl8821cu（应该兼容rtl8811cu），用@ophub的源码打包，但是插入网卡后，「网络」菜单没有「无线」选项，网卡能被识别，但不能正常工作，@ophub大佬说过「op的原内核被f大的内核替换了，驱动以f大的为准」，所以过来请教一下。

`......
Thu Mar 16 10:19:33 2023 kern.info kernel: [  192.051522] usb 1-1: new high-speed USB device number 2 using xhci-hcd
Thu Mar 16 10:19:33 2023 kern.info kernel: [  192.195198] usb 1-1: New USB device found, idVendor=0bda, idProduct=c811, bcdDevice= 2.00
Thu Mar 16 10:19:33 2023 kern.info kernel: [  192.204692] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Thu Mar 16 10:19:33 2023 kern.info kernel: [  192.211776] usb 1-1: Product: 802.11ac NIC
Thu Mar 16 10:19:33 2023 kern.info kernel: [  192.215818] usb 1-1: Manufacturer: Realtek
Thu Mar 16 10:19:33 2023 kern.info kernel: [  192.219864] usb 1-1: SerialNumber: 123456
root@OpenWrt:~# lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux 5.15.100-flippy-82+o xhci-hcd xHCI Host Controller
Bus 001 Device 002: ID 0bda:c811 Realtek 802.11ac NIC
Bus 001 Device 001: ID 1d6b:0002 Linux 5.15.100-flippy-82+o xhci-hcd xHCI Host Controller
root@OpenWrt:~# ifconfig -a
br-lan    Link encap:Ethernet  HWaddr 32:A3:24:10:7B:F2  
          inet addr:192.168.1.1  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::30a3:24ff:fe10:7bf2/64 Scope:Link
          inet6 addr: fd14:2e61:d1cc::1/60 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:6235 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4542 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:713602 (696.8 KiB)  TX bytes:1116548 (1.0 MiB)

docker0   Link encap:Ethernet  HWaddr 02:42:25:D5:86:50  
          inet addr:172.17.0.1  Bcast:172.17.255.255  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

dummy0    Link encap:Ethernet  HWaddr CE:FA:3F:0A:44:49  
          BROADCAST NOARP  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

erspan0   Link encap:Ethernet  HWaddr 00:00:00:00:00:00  
          BROADCAST MULTICAST  MTU:1450  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth0      Link encap:Ethernet  HWaddr 32:A3:24:10:7B:F2  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:6243 errors:0 dropped:8 overruns:0 frame:0
          TX packets:4648 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:809037 (790.0 KiB)  TX bytes:1119935 (1.0 MiB)
          Interrupt:30 

gre0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          NOARP  MTU:1476  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

gretap0   Link encap:Ethernet  HWaddr 00:00:00:00:00:00  
          BROADCAST MULTICAST  MTU:1462  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

ip6tnl0   Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          NOARP  MTU:1452  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:388 errors:0 dropped:0 overruns:0 frame:0
          TX packets:388 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:37493 (36.6 KiB)  TX bytes:37493 (36.6 KiB)

sit0      Link encap:IPv6-in-IPv4  
          NOARP  MTU:1480  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)`

**Comment by xinlingduyu** [comment]
我也遇到过这样的问题，就是利用lede源码编译，明明选择了以下USB网卡驱动，通过打包后，居然无法识别，插入usb 8153反而能识别驱动，USB除了下面几个选择了，其他都没选择！
                               -> kmod-usb-net-asix    
                               -> kmod-usb-net-asix-ax88179
                               -> kmod-usb2
                               -> kmod-usb3

**Comment by xinlingduyu** [comment]
我的问题解决了，f大打包源码默认内核是6.1.18的，我换成5.15.100成功识别

**Comment by gforce1206** [comment]
> 我的问题解决了，f大打包源码默认内核是6.1.18的，我换成5.15.100成功识别

你的是有线网卡吧，我说的是无线网卡

**Comment by xinlingduyu** [comment]
> > 我的问题解决了，f大打包源码默认内核是6.1.18的，我换成5.15.100成功识别
> 
> 你的是有线网卡吧，我说的是无线网卡

我的是usb3.0接口转千兆有线网卡
