### ISSUE TITLE
PVE ARM64下运行时偶尔出现bpfilter报错, ipv4无法上网

### ISSUE THREAD

**Issue by happyme531** [unifreq/openwrt_packit#182]
如题.
主机为Hinlink H88K, 运行armbian bullseye,内核为5.10.110-rockchip-rk3588, PVE 7.3-6
问题似乎出现在passwall2重载节点时, 防火墙规则发生错误.

dmesg可以看到以下日志：
```bash
[ 1275.036607] bpfilter: read fail -512
[ 1275.064293] bpfilter: Loaded bpfilter_umh pid 21197
[ 1275.065005] Started bpfilter
```

之后无法通过ipv4上网, 访问管理界面, dhcp服务也没有起作用. ipv6一切正常, 可以通过ipv6 ssh连接到路由器执行service firewall restart 重启防火墙, 有概率解决问题(一次不行就多重启几次).

虚拟机镜像的内核:
```bash
uname -a
Linux OpenWrt 6.1.11-flippy-81+ #38 SMP Sun Feb 12 21:17:06 CST 2023 aarch64 GNU/Linux
```
虚拟机配置:
Something went really wrong, and we can’t process that file.

**Comment by happyme531** [comment]
https://www.jianshu.com/p/48e2f3e6caeb

**Comment by unifreq** [comment]
最近的内核已删除了bpfilter模块
