### ISSUE TITLE
云编译失败

### ISSUE THREAD

**Issue by teddy780102** [unifreq/openwrt_packit#197]
云编译错误提示跟大佬修改的文件名字貌似有关，小白一个不太清楚，求救！

**Comment by teddy780102** [comment]
Download action repository 'unifreq/openwrt_packit@master' (SHA:7bb937b58205e63e4eaa997485100ee3affa2cac)
Error: Could not find file '/home/runner/work/_actions/_temp_babd7a77-2307-4c52-99ae-3a75643c3774/_staging/unifreq-openwrt_packit-7bb937b/openwrt-armvirt-64-generic-rootfs.tar.gz'.

**Comment by wekingchen** [comment]
我也遇到了同样的问题，求解~

**Comment by quanjindeng** [comment]
+1

**Comment by xuexijiaoben** [comment]
我也是呀，求解

**Comment by xuexijiaoben** [comment]
Current runner version: '2.304.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@main' (SHA:f095bcc56b7c2baf48f3ac70d6d6782f4f553222)
Download action repository 'P3TERX/ssh2actions@v1.0.0' (SHA:71006b93bff498b020448ac10964f8a5d0f9f32c)
Download action repository 'actions/upload-artifact@main' (SHA:65d862660abb392b8c4a3d1195a2108db131dd05)
Download action repository 'unifreq/openwrt_packit@master' (SHA:dbd1a1a6a6cfb94f2f34b30ad3c077fd630a9a3d)
Error: Could not find file '/home/runner/work/_actions/_temp_4f2c3389-f4b2-4d71-9d6a-9b815c1b2406/_staging/unifreq-openwrt_packit-dbd1a1a/openwrt-armvirt-64-generic-rootfs.tar.gz'.

**Comment by ophub** [comment]
我测试正常，你试着换一下地址看看：

`uses: ophub/flippy-openwrt-actions@main`

如果这个可以正常检出的话，可能得调整这个无效的软链接。

**Comment by teddy780102** [comment]
换地址后可以继续编译

**Comment by ophub** [comment]
好的，我问问f大他新加的这个tar软连接有什么特殊考虑，调整下
