### ISSUE TITLE
我家云 RK3328 打包OpenWrt 后无法正常运行

### ISSUE THREAD

**Issue by 0xffffharry** [unifreq/openwrt_packit#246]
如题，表现为：风扇转，网口灯不亮，无法获取IP地址

**Comment by 0xffffharry** [comment]
已解决，新版本OpenWrt固件将eth0识别为end0，需要手动修改，或者在构建固件时手动更正

**Comment by Javebean** [comment]
hello 你好 我目前用ophub大佬的固件 打包的img刷入后表现和您一样 但是我没找到end0在哪里修改 您还记得吗？
