### ISSUE TITLE
不理解 install-to-emmc.sh 中为什么要删除 AdGuardHome

### ISSUE THREAD

**Issue by jshensh** [unifreq/openwrt_packit#4]
这么做是有什么特别的历史遗留问题么，但是我看 AdGuardHome 是可以正常运行的
https://github.com/unifreq/openwrt_packit/blob/d421b3b3264937002928aab0a32cc3091fb5aa37/files/s905d/install-to-emmc.sh#L466
https://github.com/unifreq/openwrt_packit/blob/d421b3b3264937002928aab0a32cc3091fb5aa37/files/s905d/install-to-emmc.sh#L575

**Comment by unifreq** [comment]
删除目录的后面又重新创建了一个软链接，这个软链接指向/mnt/mmcblk2p4/AdGuardHome作用一是不占用rootfs空间，改用共享数据分区的空间，二是升级后已下载的核心文件不会丢失发自我的华为手机-------- 原始邮件 --------发件人： 403 Forbidden ***@***.***>日期： 2021年7月4日周日 23:00收件人： unifreq/openwrt_packit ***@***.***>抄送： Subscribed ***@***.***>主    题： [unifreq/openwrt_packit] 不理解 install-to-emmc.sh 中为什么要删除 AdGuardHome (#4)

这么做是有什么特别的历史遗留问题么，但是我看 AdGuardHome 是可以正常运行的

https://github.com/unifreq/openwrt_packit/blob/d421b3b3264937002928aab0a32cc3091fb5aa37/files/s905d/install-to-emmc.sh#L466

https://github.com/unifreq/openwrt_packit/blob/d421b3b3264937002928aab0a32cc3091fb5aa37/files/s905d/install-to-emmc.sh#L575
