### ISSUE TITLE
最近打包的固件docker根目录有问题。

### ISSUE THREAD

**Issue by y9858** [unifreq/openwrt_packit#57]
![new](https://user-images.githubusercontent.com/53130835/148002736-7ab5e339-54ac-4eb7-9ae0-d47dbf15b6a6.png)
换回12月3号的打包源码，正常。
![old](https://user-images.githubusercontent.com/53130835/148002750-7680ec12-a23f-4d6e-a8f6-63f687d0584a.png)

**Comment by unifreq** [comment]
这是从u盘写入emmc后才会出现的，手动更改一次就好了
