### ISSUE TITLE
文件在什么地方下载？

### ISSUE THREAD

**Issue by liubangjian** [unifreq/openwrt_packit#6]
自己编译的 openwrt rootfs tar.gz 包： openwrt-armvirt-64-default-rootfs.tar.gz
在什么地方下载？
把编译好的 openwrt-armvirt-64-default-rootfs.tar.gz 上传至 /opt/openwrt_packit目录中
在什么地方下载 ？

**Comment by unifreq** [comment]
自己编译发自我的华为手机-------- 原始邮件 --------发件人： liubangjian ***@***.***>日期： 2021年7月8日周四 16:21收件人： unifreq/openwrt_packit ***@***.***>抄送： Subscribed ***@***.***>主    题： [unifreq/openwrt_packit] 文件在什么地方下载？ (#6)

自己编译的 openwrt rootfs tar.gz 包： openwrt-armvirt-64-default-rootfs.tar.gz

在什么地方下载？

把编译好的 openwrt-armvirt-64-default-rootfs.tar.gz 上传至 /opt/openwrt_packit目录中

在什么地方下载 ？

**Comment by unifreq** [comment]
这没有下载的，需要自己编译，提倡diy精神。编译的源码和方法参见 https://github.com/coolsnowwolf/lede
