### ISSUE TITLE
WSL2打包报错，以前的打包源码没问题

### ISSUE THREAD

**Issue by YY-China** [unifreq/openwrt_packit#68]
挂载 /dev/loop2p1 --> /home/yy/arm-box/tmp/tmp.CI5qr4GteC/tgt_boot ... 成功
挂载 /dev/loop2p2 --> /home/yy/arm-box/tmp/tmp.CI5qr4GteC/tgt_root ... 成功
创建 /etc 子卷 ...
Create subvolume '/home/yy/arm-box/tmp/tmp.CI5qr4GteC/tgt_root/etc'
释放 Openwrt rootfs 压缩包 ... 完成
裁减 Rootfs 中用不到的文件 ... 完成
重新链接 kmod 程序 ... 完成
释放 Armbian firmware 压缩包 ... 完成
复制 Added firmware 文件 ... 完成
优化 firmware ... 完成
释放 Kernel modules 压缩包 ... 完成
复制硬件机型数据库 ...
'/home/yy/arm-box/files/amlogic_model_database.txt' -> '/home/yy/arm-box/tmp/tmp.CI5qr4GteC/tgt_root/etc/model_database.txt'
完成
释放 Kernel zImage、uInitrd 及 dtbs 压缩包 ... cp: cannot create regular file './aml_autoscript.cmd:Zone.Identifier': Invalid argument
**cp: cannot create regular file './boot.cmd:Zone.Identifier': Invalid argument
cp: cannot create regular file './boot-emmc.cmd:Zone.Identifier': Invalid argument
cp: cannot create regular file './boot-emmc.scr:Zone.Identifier': Invalid argument
cp: cannot create regular file './boot.scr:Zone.Identifier': Invalid argument
cp: cannot create regular file './emmc_autoscript.cmd:Zone.Identifier': Invalid argument
cp: cannot create regular file './s905_autoscript.cmd:Zone.Identifier': Invalid argument**
失败！

**Comment by unifreq** [comment]
是不是你的硬盘满了？

**Comment by YY-China** [comment]
> 是不是你的硬盘满了？

绝对不会是这个原因，**Invalid argument**应该表示的是Linux特殊字符的处理可能有点问题，比如说创建文件的时候一些冒号、引号之类的，大佬看看能不能脚本调优下

**Comment by sajati** [comment]
*.zone.Identifier file is files that automatically created when you copy from windows to linux (wsl), i had to clean it everytime copying files from windows to linux, also beware of editing linux files in windows, i have to convert it with `dos2unix` to avoid problems.
