### ISSUE TITLE
Building u-boot 

### ISSUE THREAD

**Issue by markus-li** [unifreq/openwrt_packit#71]
First off, thank you for the awesome contributions to getting so many TV-boxes supported with OpenWRT.

I would like to compile even u-boot from source, would you mind sharing the patch you apply for building the mainline u-boot for x96 max+?

For creating the FIP version, any pointer to anything more specific for x96 max+ vs what can be found here would be very much appreciated:
https://u-boot.readthedocs.io/en/latest/board/amlogic/sei610.html

I assume you build them based on the official repo?:
https://github.com/u-boot/u-boot/

Thank you in advance!
-Markus

**Comment by unifreq** [comment]
Thanks for your suggestion, I can provide u-boot patches for x96max+ and several other models, I'll clone a u-boot branch later and merge them. Maybe they're not canonical enough to go into the mainline repo, I'll try to do that.

**Comment by unifreq** [comment]
https://github.com/unifreq/amlogic-boot-fip

**Comment by markus-li** [comment]
Thank you very much! I'll dig into these soon to see about understanding the differences.
