### ISSUE TITLE
章鱼星球刷 了armbian 内核 为5.10.112，然后docker F大的openwrt,用不了

### ISSUE THREAD

**Issue by lanyucomputer** [unifreq/openwrt_packit#84]
可以启动，进去之后很多选项不显示，有的显示收集中，  显示图片如下https://github.com/lanyucomputer/openwrt2022/raw/main/unifreqopenwrtaarch64latest.png
这个图比较大，要下载了才看得全图

**Comment by lanyucomputer** [comment]
我试了很多版本的docker版本的 openwrt，只有这个 docker pull sulinggg/openwrt:aarch64_generic 可以稍微正常使用，但这个固件里面的服务程序较少，还有这个固件里面的passwall不能正常使用，希望F大测试一下，章鱼星球版的DOCKER openwrt

**Comment by unifreq** [comment]
哪些不能用？docker固件依赖宿主机的内核，有些事并不全是docker的问题。
