### ISSUE TITLE
N1打包之后运存只有1.8G

### ISSUE THREAD

**Issue by nkym233** [unifreq/openwrt_packit#85]
我用其他大佬打包的固件，运存是1.9G+,
自己打包的只有1.8，是我哪里操作有误吗？

**Comment by tsingui** [comment]
有发现类似问题，应该是不同内核保留部分内存大小，5.4.x至5.15.x内核1.8G，而5.17.x有1.9G，其实内存已经用不完了，没必要太纠结，当内存不够用时，硬件性能也会不够……
